import Head from "next/head"
import styles from "@/styles/Home.module.css"
import { Inter } from "next/font/google"
import { useCallback, useEffect, useMemo, useState } from "react"
import Colorbox from "@/components/colorbox"

const inter = Inter({ subsets: ["latin"] })

const arrayColor = ["yellow", "red", "green", "blue"]
const randomColor = () => {
    let randomNumber = Math.floor(Math.random() * 4)
    return arrayColor[randomNumber]
}

const SimonGame = () => {
    const [sequence, setSequence] = useState<string[]>(["red", "red"])
    const [position, setPosition] = useState<number>(0)
    const [isComputer, setIsComputer] = useState<boolean>(true)
    const [pause, setPause] = useState<boolean>(false)
    
    const colorToLight = useMemo(
        () => {
            return sequence[position]
        }, [sequence, position])

    console.log('state', sequence, position, isComputer, pause)

    useEffect(() => {
        if(pause){
           setTimeout(() => {
            setPause(false)
           }, 200) 
        }
    }, [pause])

    useEffect(
        () => {
            if(isComputer){
                if (position < sequence.length){
                    if(!pause){
                        setTimeout(() => {
                            setPosition(position + 1)
                            setPause(true)
                        }, 1000)
                    }
                }
                else {
                    setPause(false)
                    setIsComputer(false)
                    setPosition(0)
                    console.log("position après timeout", position)
                }
            }
        }, [position, sequence.length, isComputer, pause]
    )

    const handleColorClick = useCallback(
        (clickedColor: string) => {
            if (clickedColor === colorToLight) {
                if (position === sequence.length - 1) {
                    const newColorArray = [...sequence, randomColor()]
                    console.log(newColorArray)
                    setSequence(newColorArray)
                    setPosition(0)
                    setIsComputer(true)
                } 
                else {
                    setPosition(position + 1)
                }                
            } 
            else {
                setPosition(0)
                const newGame = [randomColor()]
                setSequence(newGame)
                setIsComputer(true)
            }
            
            
        }, [position, sequence, isComputer]
    )

 

    return (
        <>
            <Head>
                <title>Jeu du Simon</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className={`${styles.main} ${inter.className}`}>
                <h1 className={`${styles.title}`}>Jeu du simon</h1>
                <div className={`${styles.gameContainer}`}>
                    {arrayColor.map(
                        (color, index) => (
                            <Colorbox 
                                key={index} 
                                className={`${styles.colorbox} ${styles[`${color}box`]} ${isComputer && !pause && colorToLight === color ? styles[`${color}box`] : styles.darker}`} 
                                onClick={() => handleColorClick(color)} 
                                color={color}
                            />
                        )
                    )}
                </div>
            </main>
        </>
    )
}

export default SimonGame