import { useSession } from "next-auth/react"
import Head from "next/head"
import styles from "@/styles/Home.module.css";
import { useCallback, useEffect, useMemo, useState } from "react"
import { Inter } from "next/font/google";
import { Prisma, PrismaClient } from "@prisma/client";
import { useRouter } from "next/router";

const inter = Inter({ subsets: ["latin"] });

const AddTodo = () => {
  const router = useRouter()
  const [inputValue, setInputValue] = useState("")
  const { data: session, status } = useSession()

  const prisma = new PrismaClient()


  const handleInputChange = useCallback(
    (e: React.ChangeEvent<HTMLInputElement>) => {
      setInputValue(e.target.value)
    }, [])

  const handleAddButtonClick = () => {
    addTask()
    router.push('/alltodos')
  }

  const addTask = async () => {
    if (session) {
      try {
        const userIdFind = await prisma.user.findUnique({
          where : { name: session.user?.name! },
          select: {id: true}
        })

        if (!userIdFind) {
          console.error("ID introuvable")
          return
        }
        const userId: number = userIdFind.id

        await prisma.todo.create({
          data: {
            title: inputValue,
            completed: false,
            userId: userId
          }
        })
        setInputValue("")
      } catch(error) {
        console.error("Erreur ajout tâche", error)
      }
    }

  }

  return (
    <>
      <Head>
        <title>Todo</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
            <h1>Ajouter une tâche</h1>
            <label htmlFor="addTask">Nouvelle tâche</label>
            <input type="text" name="addTask" onChange={handleInputChange}/>
            <button onClick={() => handleAddButtonClick}>Ajouter</button>
      </main>
    </>
  )
}

export default AddTodo
