import Head from "next/head";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import { signIn, signOut, useSession } from "next-auth/react";
import Link from "next/link";


const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const { data: session, status } = useSession()

  return (
    <>
      <Head>
        <title>Todo</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <div className={`${styles.description}`}>
          {status === "unauthenticated" && <button onClick={() => signIn()}>Sign In</button>}
          {status === "authenticated" && <button onClick={() => signOut()}>Sign Out</button>}
        </div>
        <div className={`${styles.content}`}>
          <h1>To Do List</h1>
          <Link href="/addtodo">Ajouter une nouvelle tâche</Link>
          <Link href="/modifytodo">Modifier une tâche</Link>
        </div>
      </main>
    </>
  );
}
