import Head from "next/head";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import { signIn, signOut, useSession } from "next-auth/react";
import Link from "next/link";
import { useCallback, useEffect, useState } from "react";
import { Prisma, PrismaClient } from "@prisma/client";

const prisma = new PrismaClient()

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const [user, setUser] = useState<string | null>(null)
  const { data: session, status } = useSession()

  useEffect(() => {
    setUser(session?.user!.name! || null)
    findOrCreateUser()
  }, [])


  const findOrCreateUser = async () => {
    try {
      if (user) {
        const existingUser = await prisma.user.findUnique({
          where: {
            name: user,
          },
        });

        if (existingUser) {
          console.log("Utilisateur existant :", existingUser)
        } else {
          await createUser()
        }
      }
    } catch (error) {
      console.error('Erreur lors de la recherche :', error);
    }
  }

  const createUser = async () => {
    try {
      if (user) {
        const newUser = await prisma.user.create({
          data: {
            name: user,
          }
        })
        console.log("Nouvel utilisateur crée :", newUser)
      }
    } catch(error) {
      console.error('Erreur à la création de user :', error)
    }
  }

  return (
    <>
      <Head>
        <title>Todo</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <div className={`${styles.description}`}>
          {status === "unauthenticated" && <button onClick={() => signIn()}>Sign In</button>}
          {status === "authenticated" && <button onClick={() => signOut()}>Sign Out</button>}
        </div>
        <div className={`${styles.content}`}>
          <h1>To Do List</h1>
          <Link href="/addtodo">Ajouter une nouvelle tâche</Link>
          <Link href="/modifytodo">Modifier une tâche</Link>
        </div>
      </main>
    </>
  );
}
