import Head from "next/head"
import styles from "@/styles/Home.module.css"
import { useCallback, useState } from "react"

const ModifyTodo = () => {

  const [inputValue, setInputValue] = useState("")

  const handleInputChange = useCallback(
    (e: React.ChangeEvent<HTMLInputElement>) => {
      setInputValue(e.target.value)
    }, [])



  return (
    <>
      <Head>
        <title>Todo</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main}`}>
        <h1>Modifier la tâche</h1>
        <label htmlFor="modifytask"></label>
        <input type="text" name="modifytask" onChange={handleInputChange}/>
        <button>Modifier</button>
      </main>
    </>
  )
}

export default ModifyTodo
